"""media metadata

Revision ID: 1f4d15661b4d
Revises: f3ce50a92fe1
Create Date: 2024-07-25 19:54:30.098946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f4d15661b4d'
down_revision: Union[str, None] = 'f3ce50a92fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_metadata',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('audio', 'video', 'image', 'document', name='mediatype'), nullable=False),
    sa.Column('transcript', sa.UnicodeText(), nullable=True),
    sa.Column('media_length', sa.Integer(), nullable=True),
    sa.Column('media_length_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_metadata')
    # ### end Alembic commands ###
