"""media dimensions

Revision ID: 85f30b085401
Revises: 1f4d15661b4d
Create Date: 2024-07-26 17:53:21.454620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f30b085401'
down_revision: Union[str, None] = '1f4d15661b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_metadata', sa.Column('media_width', sa.Integer(), nullable=True))
    op.add_column('media_metadata', sa.Column('media_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_metadata', 'media_height')
    op.drop_column('media_metadata', 'media_width')
    # ### end Alembic commands ###
