"""file mime

Revision ID: f3ce50a92fe1
Revises: c13381b24e23
Create Date: 2024-07-25 18:16:51.113142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ce50a92fe1'
down_revision: Union[str, None] = 'c13381b24e23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('mime', sa.String(), nullable=True))
    op.drop_column('files', 'extension')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('files', 'mime')
    # ### end Alembic commands ###
